[env:esp32-s3-n16]
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200

board_build.flash_mode = dio
board_build.flash_size = 16MB

build_flags =
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0